<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\ContainerSxkvaiz\appProdProjectContainer::class, false)) {
    require __DIR__.'/ContainerSxkvaiz/appProdProjectContainer.php';
}

if (!class_exists(appProdProjectContainer::class, false)) {
    class_alias(\ContainerSxkvaiz\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerSxkvaiz\appProdProjectContainer();
