<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\ContainerNy7vmoe\appDevDebugProjectContainer::class, false)) {
    require __DIR__.'/ContainerNy7vmoe/appDevDebugProjectContainer.php';
}

if (!class_exists(appDevDebugProjectContainer::class, false)) {
    class_alias(\ContainerNy7vmoe\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerNy7vmoe\appDevDebugProjectContainer();
