<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Faktury extends \AppBundle\Entity\Faktury implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Faktury' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Faktury' . "\0" . 'rodzaj', '' . "\0" . 'AppBundle\\Entity\\Faktury' . "\0" . 'naszaFirmaId', '' . "\0" . 'AppBundle\\Entity\\Faktury' . "\0" . 'kontrahentNip', '' . "\0" . 'AppBundle\\Entity\\Faktury' . "\0" . 'kontrahentNazwa', '' . "\0" . 'AppBundle\\Entity\\Faktury' . "\0" . 'kontrahentAdres', '' . "\0" . 'AppBundle\\Entity\\Faktury' . "\0" . 'kontrahentMiasto', '' . "\0" . 'AppBundle\\Entity\\Faktury' . "\0" . 'kontrahentKodPocztowy', '' . "\0" . 'AppBundle\\Entity\\Faktury' . "\0" . 'numer', '' . "\0" . 'AppBundle\\Entity\\Faktury' . "\0" . 'dataWystawienia', '' . "\0" . 'AppBundle\\Entity\\Faktury' . "\0" . 'kontrahentNrKonta', '' . "\0" . 'AppBundle\\Entity\\Faktury' . "\0" . 'kwotaNetto', '' . "\0" . 'AppBundle\\Entity\\Faktury' . "\0" . 'kwotaBrutto', '' . "\0" . 'AppBundle\\Entity\\Faktury' . "\0" . 'kwotaVat', '' . "\0" . 'AppBundle\\Entity\\Faktury' . "\0" . 'opis', '' . "\0" . 'AppBundle\\Entity\\Faktury' . "\0" . 'formaPlatnosci', '' . "\0" . 'AppBundle\\Entity\\Faktury' . "\0" . 'plikSkanFaktury', '' . "\0" . 'AppBundle\\Entity\\Faktury' . "\0" . 'czyZaplacono', '' . "\0" . 'AppBundle\\Entity\\Faktury' . "\0" . 'terminPlatnosci', '' . "\0" . 'AppBundle\\Entity\\Faktury' . "\0" . 'projekt'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Faktury' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Faktury' . "\0" . 'rodzaj', '' . "\0" . 'AppBundle\\Entity\\Faktury' . "\0" . 'naszaFirmaId', '' . "\0" . 'AppBundle\\Entity\\Faktury' . "\0" . 'kontrahentNip', '' . "\0" . 'AppBundle\\Entity\\Faktury' . "\0" . 'kontrahentNazwa', '' . "\0" . 'AppBundle\\Entity\\Faktury' . "\0" . 'kontrahentAdres', '' . "\0" . 'AppBundle\\Entity\\Faktury' . "\0" . 'kontrahentMiasto', '' . "\0" . 'AppBundle\\Entity\\Faktury' . "\0" . 'kontrahentKodPocztowy', '' . "\0" . 'AppBundle\\Entity\\Faktury' . "\0" . 'numer', '' . "\0" . 'AppBundle\\Entity\\Faktury' . "\0" . 'dataWystawienia', '' . "\0" . 'AppBundle\\Entity\\Faktury' . "\0" . 'kontrahentNrKonta', '' . "\0" . 'AppBundle\\Entity\\Faktury' . "\0" . 'kwotaNetto', '' . "\0" . 'AppBundle\\Entity\\Faktury' . "\0" . 'kwotaBrutto', '' . "\0" . 'AppBundle\\Entity\\Faktury' . "\0" . 'kwotaVat', '' . "\0" . 'AppBundle\\Entity\\Faktury' . "\0" . 'opis', '' . "\0" . 'AppBundle\\Entity\\Faktury' . "\0" . 'formaPlatnosci', '' . "\0" . 'AppBundle\\Entity\\Faktury' . "\0" . 'plikSkanFaktury', '' . "\0" . 'AppBundle\\Entity\\Faktury' . "\0" . 'czyZaplacono', '' . "\0" . 'AppBundle\\Entity\\Faktury' . "\0" . 'terminPlatnosci', '' . "\0" . 'AppBundle\\Entity\\Faktury' . "\0" . 'projekt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Faktury $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setRodzaj($rodzaj)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRodzaj', [$rodzaj]);

        return parent::setRodzaj($rodzaj);
    }

    /**
     * {@inheritDoc}
     */
    public function getRodzaj()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRodzaj', []);

        return parent::getRodzaj();
    }

    /**
     * {@inheritDoc}
     */
    public function setNaszaFirmaId($naszaFirmaId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNaszaFirmaId', [$naszaFirmaId]);

        return parent::setNaszaFirmaId($naszaFirmaId);
    }

    /**
     * {@inheritDoc}
     */
    public function getNaszaFirmaId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNaszaFirmaId', []);

        return parent::getNaszaFirmaId();
    }

    /**
     * {@inheritDoc}
     */
    public function getKontrahentNip()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKontrahentNip', []);

        return parent::getKontrahentNip();
    }

    /**
     * {@inheritDoc}
     */
    public function setKontrahentNip($kontrahentNip)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKontrahentNip', [$kontrahentNip]);

        return parent::setKontrahentNip($kontrahentNip);
    }

    /**
     * {@inheritDoc}
     */
    public function getKontrahentNazwa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKontrahentNazwa', []);

        return parent::getKontrahentNazwa();
    }

    /**
     * {@inheritDoc}
     */
    public function setKontrahentNazwa($kontrahentNazwa)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKontrahentNazwa', [$kontrahentNazwa]);

        return parent::setKontrahentNazwa($kontrahentNazwa);
    }

    /**
     * {@inheritDoc}
     */
    public function getKontrahentAdres()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKontrahentAdres', []);

        return parent::getKontrahentAdres();
    }

    /**
     * {@inheritDoc}
     */
    public function setKontrahentAdres($kontrahentAdres)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKontrahentAdres', [$kontrahentAdres]);

        return parent::setKontrahentAdres($kontrahentAdres);
    }

    /**
     * {@inheritDoc}
     */
    public function getKontrahentMiasto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKontrahentMiasto', []);

        return parent::getKontrahentMiasto();
    }

    /**
     * {@inheritDoc}
     */
    public function setKontrahentMiasto($kontrahentMiasto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKontrahentMiasto', [$kontrahentMiasto]);

        return parent::setKontrahentMiasto($kontrahentMiasto);
    }

    /**
     * {@inheritDoc}
     */
    public function getKontrahentKodPocztowy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKontrahentKodPocztowy', []);

        return parent::getKontrahentKodPocztowy();
    }

    /**
     * {@inheritDoc}
     */
    public function setKontrahentKodPocztowy($kontrahentKodPocztowy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKontrahentKodPocztowy', [$kontrahentKodPocztowy]);

        return parent::setKontrahentKodPocztowy($kontrahentKodPocztowy);
    }

    /**
     * {@inheritDoc}
     */
    public function setNumer($numer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumer', [$numer]);

        return parent::setNumer($numer);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumer', []);

        return parent::getNumer();
    }

    /**
     * {@inheritDoc}
     */
    public function setDataWystawienia($dataWystawienia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDataWystawienia', [$dataWystawienia]);

        return parent::setDataWystawienia($dataWystawienia);
    }

    /**
     * {@inheritDoc}
     */
    public function getDataWystawienia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDataWystawienia', []);

        return parent::getDataWystawienia();
    }

    /**
     * {@inheritDoc}
     */
    public function setKontrahentNrKonta($kontrahentNrKonta)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKontrahentNrKonta', [$kontrahentNrKonta]);

        return parent::setKontrahentNrKonta($kontrahentNrKonta);
    }

    /**
     * {@inheritDoc}
     */
    public function getKontrahentNrKonta()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKontrahentNrKonta', []);

        return parent::getKontrahentNrKonta();
    }

    /**
     * {@inheritDoc}
     */
    public function setKwotaNetto($kwotaNetto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKwotaNetto', [$kwotaNetto]);

        return parent::setKwotaNetto($kwotaNetto);
    }

    /**
     * {@inheritDoc}
     */
    public function getKwotaNetto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKwotaNetto', []);

        return parent::getKwotaNetto();
    }

    /**
     * {@inheritDoc}
     */
    public function setKwotaBrutto($kwotaBrutto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKwotaBrutto', [$kwotaBrutto]);

        return parent::setKwotaBrutto($kwotaBrutto);
    }

    /**
     * {@inheritDoc}
     */
    public function getKwotaBrutto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKwotaBrutto', []);

        return parent::getKwotaBrutto();
    }

    /**
     * {@inheritDoc}
     */
    public function setKwotaVat($kwotaVat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKwotaVat', [$kwotaVat]);

        return parent::setKwotaVat($kwotaVat);
    }

    /**
     * {@inheritDoc}
     */
    public function getKwotaVat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKwotaVat', []);

        return parent::getKwotaVat();
    }

    /**
     * {@inheritDoc}
     */
    public function setOpis($opis)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOpis', [$opis]);

        return parent::setOpis($opis);
    }

    /**
     * {@inheritDoc}
     */
    public function getOpis()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOpis', []);

        return parent::getOpis();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormaPlatnosci($formaPlatnosci)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormaPlatnosci', [$formaPlatnosci]);

        return parent::setFormaPlatnosci($formaPlatnosci);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormaPlatnosci()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormaPlatnosci', []);

        return parent::getFormaPlatnosci();
    }

    /**
     * {@inheritDoc}
     */
    public function setPlikSkanFaktury($plikSkanFaktury)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlikSkanFaktury', [$plikSkanFaktury]);

        return parent::setPlikSkanFaktury($plikSkanFaktury);
    }

    /**
     * {@inheritDoc}
     */
    public function getPlikSkanFaktury()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlikSkanFaktury', []);

        return parent::getPlikSkanFaktury();
    }

    /**
     * {@inheritDoc}
     */
    public function setCzyZaplacono($czyZaplacono)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCzyZaplacono', [$czyZaplacono]);

        return parent::setCzyZaplacono($czyZaplacono);
    }

    /**
     * {@inheritDoc}
     */
    public function getCzyZaplacono()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCzyZaplacono', []);

        return parent::getCzyZaplacono();
    }

    /**
     * {@inheritDoc}
     */
    public function getTerminPlatnosci()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTerminPlatnosci', []);

        return parent::getTerminPlatnosci();
    }

    /**
     * {@inheritDoc}
     */
    public function setTerminPlatnosci($terminPlatnosci)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTerminPlatnosci', [$terminPlatnosci]);

        return parent::setTerminPlatnosci($terminPlatnosci);
    }

    /**
     * {@inheritDoc}
     */
    public function setProjekt(\AppBundle\Entity\Projekty $projekt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProjekt', [$projekt]);

        return parent::setProjekt($projekt);
    }

    /**
     * {@inheritDoc}
     */
    public function getProjekt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProjekt', []);

        return parent::getProjekt();
    }

}
